// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: avtech-queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const writeAvtechRecord = `-- name: WriteAvtechRecord :exec
INSERT INTO
    avtech_data(id, timestamp, temp_f, temp_c, device_id, device_type_id)
VALUES (DEFAULT, $1, $2, $3, $4, $5)
`

type WriteAvtechRecordParams struct {
	Timestamp    pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	TempF        float64            `db:"temp_f" json:"temp_f"`
	TempC        float64            `db:"temp_c" json:"temp_c"`
	DeviceID     int32              `db:"device_id" json:"device_id"`
	DeviceTypeID int32              `db:"device_type_id" json:"device_type_id"`
}

func (q *Queries) WriteAvtechRecord(ctx context.Context, arg WriteAvtechRecordParams) error {
	_, err := q.db.Exec(ctx, writeAvtechRecord,
		arg.Timestamp,
		arg.TempF,
		arg.TempC,
		arg.DeviceID,
		arg.DeviceTypeID,
	)
	return err
}
