// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AmbientStationDatum struct {
	ID                    int32              `db:"id" json:"id"`
	Timestamp             pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	Date                  pgtype.Text        `db:"date" json:"date"`
	Timezone              pgtype.Text        `db:"timezone" json:"timezone"`
	DateUtc               pgtype.Int4        `db:"date_utc" json:"date_utc"`
	InsideTempF           pgtype.Float8      `db:"inside_temp_f" json:"inside_temp_f"`
	InsideTempFFeelsLike  pgtype.Float8      `db:"inside_temp_f_feels_like" json:"inside_temp_f_feels_like"`
	InsideTempC           pgtype.Float8      `db:"inside_temp_c" json:"inside_temp_c"`
	OutsideTempF          pgtype.Float8      `db:"outside_temp_f" json:"outside_temp_f"`
	OutsideTempFFeelsLike pgtype.Float8      `db:"outside_temp_f_feels_like" json:"outside_temp_f_feels_like"`
	InsideHumidity        pgtype.Float8      `db:"inside_humidity" json:"inside_humidity"`
	OutsideHumidity       pgtype.Float8      `db:"outside_humidity" json:"outside_humidity"`
	InsideDewPoint        pgtype.Float8      `db:"inside_dew_point" json:"inside_dew_point"`
	OutsideDewPoint       pgtype.Float8      `db:"outside_dew_point" json:"outside_dew_point"`
	BarometricRelative    pgtype.Float8      `db:"barometric_relative" json:"barometric_relative"`
	BarometricAbsolute    pgtype.Float8      `db:"barometric_absolute" json:"barometric_absolute"`
	WindDirection         pgtype.Float8      `db:"wind_direction" json:"wind_direction"`
	WindSpeedMph          pgtype.Float8      `db:"wind_speed_mph" json:"wind_speed_mph"`
	WindGustMph           pgtype.Float8      `db:"wind_gust_mph" json:"wind_gust_mph"`
	MaxDailyGustMph       pgtype.Float8      `db:"max_daily_gust_mph" json:"max_daily_gust_mph"`
	HourlyRainInches      pgtype.Float8      `db:"hourly_rain_inches" json:"hourly_rain_inches"`
	EventRainInches       pgtype.Float8      `db:"event_rain_inches" json:"event_rain_inches"`
	DailyRainInches       pgtype.Float8      `db:"daily_rain_inches" json:"daily_rain_inches"`
	WeeklyRainInches      pgtype.Float8      `db:"weekly_rain_inches" json:"weekly_rain_inches"`
	MonthlyRainInches     pgtype.Float8      `db:"monthly_rain_inches" json:"monthly_rain_inches"`
	TotalRainInches       pgtype.Float8      `db:"total_rain_inches" json:"total_rain_inches"`
	UvIndex               pgtype.Float8      `db:"uv_index" json:"uv_index"`
	SolarRadiation        pgtype.Float8      `db:"solar_radiation" json:"solar_radiation"`
	OutsideBattStatus     pgtype.Int4        `db:"outside_batt_status" json:"outside_batt_status"`
	Co2BatStatus          pgtype.Int4        `db:"co2_bat_status" json:"co2_bat_status"`
	DeviceID              pgtype.Int4        `db:"device_id" json:"device_id"`
	DeviceTypeID          pgtype.Int4        `db:"device_type_id" json:"device_type_id"`
}

type AvtechDatum struct {
	ID           int32              `db:"id" json:"id"`
	Timestamp    pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	TempF        float64            `db:"temp_f" json:"temp_f"`
	TempC        float64            `db:"temp_c" json:"temp_c"`
	Humidity     float64            `db:"humidity" json:"humidity"`
	DeviceID     int32              `db:"device_id" json:"device_id"`
	DeviceTypeID int32              `db:"device_type_id" json:"device_type_id"`
}

type DeviceList struct {
	ID           int32       `db:"id" json:"id"`
	DeviceName   string      `db:"device_name" json:"device_name"`
	Location     pgtype.Text `db:"location" json:"location"`
	IpAddress    pgtype.Text `db:"ip_address" json:"ip_address"`
	DeviceTypeID int32       `db:"device_type_id" json:"device_type_id"`
	// Enables data collection for this device
	Enabled pgtype.Bool `db:"enabled" json:"enabled"`
}

type DeviceType struct {
	ID         int32  `db:"id" json:"id"`
	DeviceType string `db:"device_type" json:"device_type"`
}
